v1 = input('Digite algo: ')
print(f'O tipo primitivo é: {type(v1)}')
print(f'é uma letra: {v1.isalpha()}')
print(f'é um numero: {v1.isnumeric()}')
print(f'tem casa decimal: {v1.isdecimal()}')
print(f'é minuscula: {v1.islower()}')
print(f'é maiscula: {v1.isupper()}')
